### ISSUE TITLE
ti_paga dropping cells

### ISSUE THREAD

**Issue by bjreisman** [dynverse/ti_paga#3]
Thanks for your work on the windows fix for HDF5! I've got the package up and running and am able to run the examples. However, I'm running into the following error when I try to run the `ti_paga()` or `ti_paga_tree()` methods:

```
> model_paga <- infer_trajectory(dataset, ti_paga(), verbose = TRUE)
Executing 'paga' on '20190407_091205__data_wrapper__W9bxxgkRKv'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "fa", connectivity_cutoff = 0.05),
inputs: counts, and
priors : start_id
Input saved to C:\Users\reismab\AppData\Local\Temp\RtmpMRCcFr\file3f403be16776/ti
Running "C:\PROGRA~1\Docker\Docker\RESOUR~1\bin\docker.exe" run -e "TMPDIR=/tmp2" --workdir /ti/workspace -v \
  "/c/Users/reismab/AppData/Local/Temp/RtmpMRCcFr/file3f403be16776/ti:/ti" -v "/c/Users/reismab/AppData/Local/Temp/RtmpMRCcFr/file3f402d1b6a91/tmp:/tmp2" \
  "dynverse/ti_paga:v0.9.9.01" --dataset /ti/input.h5 --output /ti/output.h5
Traceback (most recent call last):
  File "/code/run.py", line 102, in <module>
    grouping = pd.DataFrame({"cell_id": counts.index, "group_id": adata.obs.louvain})
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 328, in extract_index
    raise ValueError(msg)
ValueError: array length 30000 does not match index length 29985
```

It seems like its dropping 15 cells at some point inside the docker container. Unfortunately, I'm not able to find the point where the error is occurring using `debug()`. 

I also tried `ti_comp1()` and `ti_mst()` which didn't throw any errors 🙌 .

Caveat: this is mass-cytometry data (24 markers, 30K cells) which I've prepared using `wrap_expression` on the raw counts and asinh transformed data. 

I've attached the data I'm having trouble with here: [pagainput.zip](https://github.com/dynverse/ti_paga/files/3051673/pagainput.zip)

**Comment by zouter** [comment]
Hi Benjamin

Managed to reproduce the error using a small example. As I imagined, scanpy is probably filtering out cells with all zero counts:

```r
library(dyno)

dataset <- dyntoy::generate_dataset(model = "linear")

dataset$counts[1:10, ] <- 0
dataset$expression[1:10, ] <- 0

trajectory <- infer_trajectory(dataset, ti_paga(), verbose = TRUE)
```

```
Executing 'paga' on '20190408_111247__toy__k0FbKRVSSh'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "fa", connectivity_cutoff = 0.05),
inputs: counts, and
priors : start_id
Input saved to /tmp/Rtmp3tNAhx/file5c933a4d200e/ti
Running method using babelwhaleRunning /usr/bin/docker run -e 'TMPDIR=/tmp2' --workdir /ti/workspace -v '/tmp/Rtmp3tNAhx/file5c933a4d200e/ti:/ti' -v \
  '/tmp/Rtmp3tNAhx/file5c935037d77d/tmp:/tmp2' 'dynverse/ti_paga:v0.9.9' --dataset /ti/input.h5 --output /ti/output.h5
Traceback (most recent call last):
  File "/code/run.py", line 102, in <module>
    grouping = pd.DataFrame({"cell_id": counts.index, "group_id": adata.obs.louvain})
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 328, in extract_index
    raise ValueError(msg)
ValueError: array length 99 does not match index length 89
Error: Error during trajectory inference 
Traceback (most recent call last):
  File "/code/run.py", line 102, in <module>
    grouping = pd.DataFrame({"cell_id": counts.index, "group_id": adata.obs.louvain})
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 328, in extract_index
    raise ValueError(msg)
ValueError: array length 99 does not match index length 89
```

Now working on a solution, but a quick workaround for you might be to filter out zero counts cells :wink:

**Comment by zouter** [comment]
Alright, figured out a solution. New versions of the wrappers are now building: ~https://travis-ci.org/dynverse/ti_paga_tree/builds/517164224~ and ~https://travis-ci.org/dynverse/ti_paga/builds/517164302~ https://travis-ci.org/dynverse/ti_paga and https://travis-ci.org/dynverse/ti_paga_tree

**Comment by zouter** [comment]
Alright, after some wrestling matches with travis, PAGA and PAGA Tree should now work even with all-zero cells! You can try it out with `ti_paga <- dynwrap::create_ti_method_container("dynverse/ti_paga:master")`

**Comment by bjreisman** [comment]
Doh! Of course. Thanks for implementing a fix! Unfortunately, I'm still running into HD5F errors as I did in https://github.com/dynverse/dyno/issues/43, though perhaps it's made it a bit further this time? I'm getting this error on both `ti_paga` and `ti_paga_tree`, but `ti_comp1` and `ti_mst` work well on both the toy dataset and my real data so I don't think its a problem with dynutils. 

P.S. love the dyntoy package, great for making repexs!
```
> library(dyno)
> 
> data <- dyntoy::generate_dataset(
+   id = "specific_example/paga",
+   num_cells = 99,
+   num_features = 101,
+   model = "tree",
+   normalise = FALSE
+ )
> ti_paga <- dynwrap::create_ti_method_container("dynverse/ti_paga:master")
> model_toy <- infer_trajectory(data, ti_paga(), verbose = TRUE)
Executing 'paga' on 'specific_example/paga'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "fa", connectivity_cutoff = 0.05),
inputs: counts, and
priors : start_id
Input saved to C:\Users\benja\AppData\Local\Temp\RtmpeAtA7B\file871c5f037baf/ti
Running "C:\PROGRA~1\Docker\Docker\RESOUR~1\bin\docker.exe" run -e "TMPDIR=/tmp2" --workdir /ti/workspace -v \
  "/c/Users/benja/AppData/Local/Temp/RtmpeAtA7B/file871c5f037baf/ti:/ti" -v "/c/Users/benja/AppData/Local/Temp/RtmpeAtA7B/file871c5ddd4631/tmp:/tmp2" \
  "dynverse/ti_paga:master" --dataset /ti/input.h5 --output /ti/output.h5
Error: Error during trajectory inference 
HDF5-API Errors:
    error #000: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5Tget_native_type(): line 119: cannot retrieve native type
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #001: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5T_get_native_type(): line 400: cannot get member value
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #002: C:\pkg\hdf5-1.8.14\src\H5T.c in H5T_convert(): line 4816: data type conversion failed
        class: HDF5
        major: Attribute
        minor: Unable to encode value

    error #003: C:\pkg\hdf5-1.8.14\src\H5Tconv.c in H5T__conv_i_i(): line 3639: can't find property list for ID
        class: HDF5
        major: Object atom
        minor: Unable to find atom information (already closed?)

    error #004: C:\pkg\hdf5-1.8.14\src\H5Pint.c in H5P_object_verify(): line 3381: property list is no
> model_toy <- infer_trajectory(data, ti_paga_tree(), verbose = TRUE)
> version
               _                                                 
platform       x86_64-w64-mingw32                                
arch           x86_64                                            
os             mingw32                                           
system         x86_64, mingw32                                   
status         Under development (unstable)                      
major          3                                                 
minor          6.0                                               
year           2019                                              
month          02                                                
day            22                                                
svn rev        76149                                             
language       R                                                 
version.string R Under development (unstable) (2019-02-22 r76149)
nickname       Unsuffered Consequences 
```
This is on my personal computer which is running a development version of R 3.6, but I'm running into the same error on another computer running R 3.5.2 on windows 10.

**Comment by bjreisman** [comment]
Look to be failing at this point: (line 76-80 here: [h5](https://github.com/dynverse/dynutils/blob/master/R/h5.R))
```
    rownames <- .read_h5_vec(file_h5[["rownames"]])
    colnames <- .read_h5_vec(file_h5[["colnames"]])
    data <- file_h5[["data"]]
    out <- map(colnames, ~.read_h5_vec(data[[.]])) %>% data.frame(check.names = FALSE, 
      stringsAsFactors = FALSE)
    rownames(out) <- rownames
    colnames(out) <- colnames
    out
```
```
Browse[3]> colnames
[1] "from"     "to"       "length"   "directed"
Browse[3]> .read_h5_vec(data[[colnames[[4]]]])
Error in standalone_H5D_get_type(h5d_id = self$id, native = TRUE) : 
  HDF5-API Errors:
    error #000: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5Tget_native_type(): line 119: cannot retrieve native type
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #001: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5T_get_native_type(): line 400: cannot get member value
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #002: C:\pkg\hdf5-1.8.14\src\H5T.c in H5T_convert(): line 4816: data type conversion failed
        class: HDF5
        major: Attribute
        minor: Unable to encode value

    error #003: C:\pkg\hdf5-1.8.14\src\H5Tconv.c in H5T__conv_i_i(): line 3639: can't find property list for ID
        class: HDF5
        major: Object atom
        minor: Unable to find atom information (already closed?)

    error #004: C:\pkg\hdf5-1.8.14\src\H5Pint.c in H5P_object_verify(): line 3381: property list is not a member of the class
        class
```
Perhaps due to this line? https://github.com/dynverse/ti_paga/blob/093f04eee608c6fb30a0975a382565c6c58bd52b/run.py#L135

edit: as well as here (found after I powered through the above error). 
```
Browse[3]> colnames
[1] "divergence_id" "milestone_id"  "is_start"     
Browse[3]> .read_h5_vec(data[[colnames[3]]])
Error in standalone_H5D_get_type(h5d_id = self$id, native = native) : 
  HDF5-API Errors:
    error #000: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5Tget_native_type(): line 119: cannot retrieve native type
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #001: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5T_get_native_type(): line 400: cannot get member value
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #002: C:\pkg\hdf5-1.8.14\src\H5T.c in H5T_convert(): line 4816: data type conversion failed
        class: HDF5
        major: Attribute
        minor: Unable to encode value

    error #003: C:\pkg\hdf5-1.8.14\src\H5Tconv.c in H5T__conv_i_i(): line 3639: can't find property list for ID
        class: HDF5
        major: Object atom
        minor: Unable to find atom information (already closed?)

    error #004: C:\pkg\hdf5-1.8.14\src\H5Pint.c in H5P_object_verify(): line 3381: property list is not a member of the class
        class
```

**Comment by zouter** [comment]
Hmmmm strangely enough, this is again the same error as dynverse/dyno#43 but this should be fixed in the latest version of the containers. Could you perhaps try with
`ti_paga <- dynwrap::create_ti_method_container("dynverse/ti_paga:v0.9.9.02")` ?

**Comment by bjreisman** [comment]
Unfortunately 0.9.9.02 didn't work for me either. (I also tried v0.9.9.01, and v0.9.9 and got the same error.)
```
> ti_paga <- dynwrap::create_ti_method_container("dynverse/ti_paga:v0.9.9.02")
> model_toy <- infer_trajectory(data, ti_paga(), verbose = TRUE)
Executing 'paga' on 'specific_example/paga'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "fa", connectivity_cutoff = 0.05),
inputs: counts, and
priors : start_id
Input saved to C:\Users\benja\AppData\Local\Temp\Rtmp4OSttO\fileb17041ba43c3/ti
Running "C:\PROGRA~1\Docker\Docker\RESOUR~1\bin\docker.exe" run -e "TMPDIR=/tmp2" --workdir /ti/workspace -v \
  "/c/Users/benja/AppData/Local/Temp/Rtmp4OSttO/fileb17041ba43c3/ti:/ti" -v \
  "/c/Users/benja/AppData/Local/Temp/Rtmp4OSttO/fileb1706f96520e/tmp:/tmp2" "dynverse/ti_paga:v0.9.9.02" --dataset /ti/input.h5 --output \
  /ti/output.h5
Error: Error during trajectory inference 
HDF5-API Errors:
    error #000: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5Tget_native_type(): line 119: cannot retrieve native type
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #001: C:\pkg\hdf5-1.8.14\src\H5Tnative.c in H5T_get_native_type(): line 400: cannot get member value
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type

    error #002: C:\pkg\hdf5-1.8.14\src\H5T.c in H5T_convert(): line 4816: data type conversion failed
        class: HDF5
        major: Attribute
        minor: Unable to encode value

    error #003: C:\pkg\hdf5-1.8.14\src\H5Tconv.c in H5T__conv_i_i(): line 3639: can't find property list for ID
        class: HDF5
        major: Object atom
        minor: Unable to find atom information (already closed?)

    error #004: C:\pkg\hdf5-1.8.14\src\H5Pint.c in H5P_object_verify(): line 3381: property list is no
```

**Comment by zouter** [comment]
Hmmm you're right, the fix is weirdly enough not yet present in dynverse/ti_paga:v0.9.9.02 .  Containers are rebuilding -> https://travis-ci.org/dynverse/ti_paga/builds/518244942

Thanks for troubleshooting :smile:

**Comment by bjreisman** [comment]
Wonderful! 🙌 
```
library(dyno)

data <- dyntoy::generate_dataset(
  id = "specific_example/paga",
  num_cells = 1000,
  num_features = 101,
  model = "tree",
  normalise = FALSE
)
model_toy <- infer_trajectory(data, ti_paga(), verbose = TRUE)
plot_dimred(model_toy)
```
![image](https://user-images.githubusercontent.com/22528952/55968829-609cda80-5c42-11e9-8fcb-de93dede01c6.png)
