### ISSUE TITLE
embedding_type = "umap" results in an error

### ISSUE THREAD

**Issue by rcannood** [dynverse/ti_paga#5]
This bug was discovered in dynverse/dynwrap#140. When embedding_type is set to "umap", ti_paga produces an error.

``` R
library(dyntoy)
toy_data <- dyntoy::generate_dataset(
  id = "specific_example/paga",
  num_cells = 1000,
  num_features = 101,
  model = "tree",
  normalise = FALSE
)
toy_model <- dynwrap::infer_trajectory(
  toy_data, 
  ti_paga(n_neighbors=15L, n_comps=50L, 
          n_dcs=15L, resolution=1L, embedding_type="umap", connectivity_cutoff=0.05), 
  verbose=TRUE
)
```
```
Executing 'paga' on 'specific_example/paga'
With parameters: list(n_neighbors = 15L, n_comps = 50L, n_dcs = 15L, resolution = 1L,     embedding_type = "umap", connectivity_cutoff = 0.05),
inputs: counts, and
priors : start_id
Input saved to /tmp/Rtmpowf4Qe/file517a3bfd6771/ti
Running method using babelwhale
Running /usr/bin/docker run -e 'TMPDIR=/tmp2' --workdir /ti/workspace -v '/tmp/Rtmpowf4Qe/file517a3bfd6771/ti:/ti' -v '/tmp/Rtmpowf4Qe/file517a504e1ec9/tmp:/tmp2' \
  'dynverse/ti_paga:v0.9.9.03' --dataset /ti/input.h5 --output /ti/output.h5 --use_priors all
Error: Error during trajectory inference 
Traceback (most recent call last):
  File "/code/run.py", line 117, in <module>
    dimred = pd.DataFrame([x for x in adata.obsm['X_umap'].T]).T
  File "/usr/local/lib/python3.7/site-packages/numpy/core/records.py", line 506, in __getitem__
    obj = super(recarray, self).__getitem__(indx)
ValueError: no field of name X_umap
```

The error occurs on [this row](https://github.com/dynverse/ti_paga/blob/master/run.py#L117).

@falexwolf Has X_umap been removed or renamed from scanpy?

**Comment by rcannood** [comment]
@falexwolf Nevermind. I think I found the problem :nerd_face:
